description: >
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #fff;
            color: #333;
            padding: 40px 20px;
            margin: 0;
        }
    
        .sidebar-content {
            background-color: #E6FFF1;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            text-align: center;
            margin: 20px auto;
        }
        
        #job-box a, .big-box, .name-box, .small-box {
            color: white;
            text-decoration: none;
            transition: transform 0.3s, opacity 0.3s;
        }
    
        #job-box a:hover, .big-box:hover, .name-box:hover, .small-box:hover {
            opacity: 0.6;
            transform: translateY(-3px);
            text-decoration: underline;  /* Consistent underline on hover */
        }

        #job-box {
            font-weight: bold;
            opacity: 0.8;
            margin: 5px 0 5px 0; /* Adjusted the margin to have 10px at the bottom */
            background-color: #00536A;
            border-radius: 15px;
            padding: 5px 10px;
            display: inline-block;
            font-size: 1.1em;
        }
            
        .big-box, .small-box {
            font-weight: bold;
            margin: 10px;
            opacity: 0.8;
            padding: 12px 30px;
            border-radius: 15px;
            display: inline-block;
            font-size: 1.1em;
            background-color: #00536A;
            width: 150px; /* added */
            height: 50px; /* added */
            text-align: center; /* added */
            line-height: 50px; /* added */
        }
        
        .name-box {            
            font-weight: bold;
            margin: 10px;
            padding: 12px 30px;
            border-radius: 15px;
            display: inline-block;
            font-size: 1.7em;
            background-color: #004e64ff;
        }
        
        .smaller-btn {
            font-size: 0.9em;
            padding: 8px 8px;
        }
    
    </style>
    
    <div class="sidebar-content">
        <div>
            <a class="name-box" href="https://scelarek.github.io">Sam Celarek</a>
        </div>
    
        <img src="/images/Circle Sam.png?raw=true" alt="Sam Celarek">
    
        <div id="job-box">
        <a href="/dsport.html">Data Scientist</a>
        |
        <a href="/daport.html">Data Analyst</a>
        </div>
    
        <div>
            Avid Data Explorer<br>
            ML Enthusiast<br>
            Coding Everyday<br>
            Medical Background<br>
            Energetic Teammate<br>
            Impact Driven<br>
        </div>
    
        <div>
            <a class="big-box" href="https://www.linkedin.com/in/sam-celarek/">LinkedIn</a>
            <a class="big-box" href="https://github.com/scelarek">GitHub</a><br>            
            <a class="big-box" href="https://calendly.com/scelarek/data-science-discussion">Book Me</a><br>
            <a class="small-box smaller-btn" href="https://drive.google.com/file/d/1Veze7DYTMwlr1_aK5hKo79kf3ZJ1Xqv5/view?usp=sharing">My Resume</a>
            <a class="small-box smaller-btn" href="mailto:scelarek@gmail.com">Email Me!</a>
        </div>
    </div>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
