description: >
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #fff;
            color: #333;
            padding: 40px 20px;
            margin: 0;
        }
    
        .sidebar-content {
            background-color: #E6FFF1;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            text-align: center;
            margin: 20px auto;
        }
    
        #name-box {
            font-weight: bold;
            color: white;
            margin: 20px 0;
            background-color: #004e64ff; /* Midnight-green */
            border-radius: 15px;
            padding: 15px 20px;
            display: inline-block;
            font-size: 1.5em; /* Increased font size */
        }
    
        .linkedin, .github, .resume {
            font-weight: bold;
            margin: 10px;
            padding: 12px 40px;
            color: white;
            text-decoration: underline; /* Added underline */
            border-radius: 15px;
            display: inline-block;
            font-size: 1.1em;
            background-color: #25A18E;
            transition: transform 0.3s, opacity 0.3s;
        }
    
        .linkedin:hover, .github:hover, .resume:hover {
            opacity: 0.9;
            transform: translateY(-3px);
        }
    
        .smaller-btn {
            font-size: 0.9em;
            padding: 8px 8px;
        }
    
        .footer-quote {
            text-align: center;
            background-color: #F3FFF8;
            padding: 20px;
            border-radius: 5px;
            margin-top: 60px; /* Increased space */
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            font-style: italic;
        }
    </style>

    <div class="sidebar-content">
        <h1>Sam Celarek</h1> <!-- This is your title -->
        <img src="/images/Circle Sam.png?raw=true" alt="Sam Celarek">
        <div id="name-box">Data Scientist</div>
        
        <div>
            Avid Data Explorer<br>
            ML Enthusiast<br>
            Coding Everyday<br>
            Strong Medical Background<br>
            Energetic Teammate<br>
            Impact Driven<br>
        </div>
        
        <div>
            <a class="linkedin" href="https://www.linkedin.com/in/sam-celarek/">LinkedIn</a>
            <a class="github" href="https://github.com/scelarek">GitHub</a><br>
            <a class="resume smaller-btn" href="https://drive.google.com/file/d/18-0YCTe0lGkdnlEGMKZrPplvkbVkRVR3/view?usp=drive_link">My Resume</a>
            <a class="resume smaller-btn" href="mailto:scelarek@gmail.com">Email Me!</a>
        </div>
    </div>
    
    <footer>
        <p class="footer-quote">“You can't actually feel the weight of the world. The human mind is not capable of that feat.
        But sometimes, you can catch a glimpse.” ― Nates Soares, On Caring</p>
    </footer>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
