description: >
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #fff;
            color: #333;
            padding: 40px 20px;
            margin: 0;
        }
    
        .sidebar-content {
            background-color: #E6FFF1;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            text-align: center;
            margin: 20px auto;
        }
    
        #title-box {
            font-weight: bold;
            color: white;
            margin: 5px 0 5px 0; /* Adjusted the margin to have 10px at the bottom */
            background-color: #00536A;
            border-radius: 5px;
            padding: 5px 10px;
            display: inline-block;
            font-size: 1.1em;
        }
        
        #title-box a, .linkedin, .github, .resume {
            color: white;
            opacity: 0.8;
            text-decoration: none;
            transition: transform 0.3s, opacity 0.3s;
        }
    
        #title-box a:hover, .linkedin:hover, .github:hover, .resume:hover {
            opacity: 0.6;
            transform: translateY(-3px);
            text-decoration: underline;  /* Consistent underline on hover */
        }
    
        .linkedin, .resume {
            font-weight: bold;
            margin: 10px;
            opacity: 0.8;
            padding: 12px 40px;
            border-radius: 15px;
            display: inline-block;
            font-size: 1.1em;
            background-color: #00536A;
        }
        .github {            
            font-weight: bold;
            margin: 10px;
            padding: 12px 40px;
            border-radius: 15px;
            display: inline-block;
            font-size: 1.5em;
            background-color: #004e64ff;
        }
        .smaller-btn {
            font-size: 0.9em;
            padding: 8px 8px;
        }
    
    </style>
    
    <div class="sidebar-content">
        <div>
            <a class="github" href="https://scelarek.github.io">Sam Celarek</a>
        </div>
    
        <img src="/images/Circle Sam.png?raw=true" alt="Sam Celarek">
    
        <div id="title-box">
        <a href="/dsport.html">Data Scientist</a>
        |
        <a href="/daport.html">Data Analyst</a>
        </div>
    
        <div>
            Avid Data Explorer<br>
            ML Enthusiast<br>
            Coding Everyday<br>
            Medical Background<br>
            Energetic Teammate<br>
            Impact Driven<br>
        </div>
    
        <div>
            <a class="linkedin" href="https://www.linkedin.com/in/sam-celarek/">LinkedIn</a>
            <a class="linkedin" href="https://github.com/scelarek">GitHub</a><br>
            <a class="resume smaller-btn" href="https://drive.google.com/file/d/1Veze7DYTMwlr1_aK5hKo79kf3ZJ1Xqv5/view?usp=sharing">My Resume</a>
            <a class="resume smaller-btn" href="mailto:scelarek@gmail.com">Email Me!</a>
        </div>
    </div>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
