title: "Sam Celarek"
logo: "/images/Circle Sam.png?raw=true"
description: >
    <style>
    body {
    font-family: Arial, sans-serif;
    background-color: #f5f5f5;
    }

    #name-box {
    background-color: gray;
    padding: 5px 10px;
    font-weight: bold;
    border-radius: 5px;
    display: block;
    margin: 20px auto;
    text-align: center;
    color: white;
    }

    .description {
    margin: 10px auto;
    padding: 10px;
    border-radius: 5px;
    background-color: rgba(240, 240, 240, 0.7);
    text-align: center; 
    }

    .linkedin, .github, .resume {
    margin: 10px;
    padding: 10px 15px;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    }

    .linkedin {
    background-color: #007BFF;
    }

    .github {
    background-color: gray;
    }

    .resume {
    background-color: #388E3C;  
    display: inline-block;  
    }

    .smaller-btn {
    font-size: 0.8em;
    padding: 6px 10px;
    border: 2px solid white;
    }

    .linkedin:hover, .github:hover, .resume:hover {
    opacity: 0.9;
    }
    </style>
    
    <div id="name-box">The Data Dude</div>
    
    <div class="description" style="text-align:center;">
        Avid Data Explorer<br>
        ML Enthusiast<br>
        Coding Everyday<br>
        Strong Medical Background<br>
        Reduced Infection Rates<br>
        Energetic Teammate
    </div>
    
    <div style="text-align: center;">
        <a class="linkedin" href="https://www.linkedin.com/in/sam-celarek/">LinkedIn</a>
        <a class="github" href="https://github.com/scelarek">GitHub</a>
    </div>
    
    <a class="resume smaller-btn" href="https://drive.google.com/file/d/1fx7HWhIajxjqvkoxQvTx0V_xDWeLU-72/view?usp=drive_link">View My Resume</a>
    <a class="resume smaller-btn" href="mailto:scelarek@gmail.com">Email Me!</a>


remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
