title: Sam Celarek
logo: "/images/Circle Sam.png?raw=true"
description: >
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
        }
    
        #name-box {
            background-color: gray;
            padding: 5px 20px;
            font-weight: bold;
            border-radius: 5px;
            display: block;
            margin: 20px auto;
            text-align: center;
            color: white;
        }
    
        .description {
            margin: 20px auto;
            padding: 20px;
            border-radius: 5px;
            background-color: rgba(240, 240, 240, 0.7);
            text-align: center; /* Center the description text */
        }
    
        .linkedin, .github, .resume {
            display: block;
            margin: 10px auto;
            padding: 10px 15px;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            width: fit-content;
        }
    
        .linkedin {
            background-color: #007BFF;
        }
    
        .github {
            background-color: gray;
        }
        
        .resume {
            background-color: #4CAF50;
        }
    
        .linkedin:hover, .github:hover, .resume:hover {
            opacity: 0.9;
        }
    </style>


    <div id="name-box">The Data Dude:</div>
    
    <div class="description" style="text-align:center;">
        Avid Data Explorer<br>
        ML Enthusiast<br>
        Coding Everyday<br>
        Strong Medical Background<br>
        Reduced Infection Rates<br>
        Energetic Teammate<br>
    </div>

    
    <a class="linkedin" href="https://www.linkedin.com/in/sam-celarek/">View My LinkedIn Profile</a>
    <a class="github" href="https://github.com/scelarek">View My GitHub Profile</a>
    <a class="resume" href="https://drive.google.com/file/d/1fx7HWhIajxjqvkoxQvTx0V_xDWeLU-72/view?usp=drive_link">View My Resume</a>
    <a class="resume" href="scelarek@gmail.com">Email Me!</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
