title: "Sam Celarek"
logo: "/images/Circle Sam.png?raw=true"
description: "A brief description about Sam Celarek."

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
