# Personal Details
title: Sam Celarek
logo: "/images/Circle Sam.png?raw=true"
description: |  # Using pipe (|) for multi-line strings, which also preserves newlines
  The Data Dude:
  
  Hello! I've been a nurse for the past 8 years, working on teams and leveraging data to enhance hospital KPIs and optimize floor staffing. After completing my BrainStation Data Science Diploma, I'm on the lookout for my first role in the industry. Take a glance at some of my data science projects below and feel free to connect!

  - [View My LinkedIn Profile](https://www.linkedin.com/in/sam-celarek/)
  - [View My GitHub Profile](https://github.com/scelarek)

# Additional configurations can be added below this line as needed


  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
