title: "Sam Celarek"
logo: "/images/Circle Sam.png?raw=true"
description: >
    <style>
    body {
        font-family: Arial, sans-serif;
        background-color: #9FFFCB;
    }

    #name-box {
        background-color: #004E64;
        padding: 5px 10px;
        font-weight: bold;
        border-radius: 5px;
        display: block;
        margin: 20px auto;
        text-align: center;
        color: white;
    }

    .description {
        margin: 20px auto;
        padding: 10px;
        border-radius: 5px;
        background-color: rgba(240, 240, 240, 0.7);
        text-align: center;
    }

    .linkedin, .github, .resume {
        margin: 15px;
        padding: 15px 45px;
        color: white;
        text-decoration: none;
        border-radius: 15px;
        display: inline-block;
    }

    .linkedin {
        background-color: #00A5CF;
    }

    .github {
        background-color: #004E64;
    }

    .resume {
        background-color: #25A18E;  
    }

    .smaller-btn {
        font-size: 0.8em;
        padding: 6px 6px;
    }

    .linkedin:hover, .github:hover, .resume:hover {
        opacity: 0.9;
    }

    .footer-quote {
        text-align: center;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        margin-top: 40px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        font-style: italic;
    }
    </style>

    <div id="name-box">Data Scientist | Impact Driven</div>

    <div class="description">
        Avid Data Explorer<br>
        ML Enthusiast<br>
        Coding Everyday<br>
        Strong Medical Background<br>
        Energetic Teammate
    </div>

    <div style="text-align: center;">
        <a class="linkedin" href="https://www.linkedin.com/in/sam-celarek/">LinkedIn</a>
        <a class="github" href="https://github.com/scelarek">GitHub</a> <br>
        <a class="resume smaller-btn" href="https://drive.google.com/file/d/18-0YCTe0lGkdnlEGMKZrPplvkbVkRVR3/view?usp=drive_link">My Resume</a>
        <a class="resume smaller-btn" href="mailto:scelarek@gmail.com">Email Me!</a>
    </div>
    <footer>
        <p class="footer-quote">“Whether the future is wonderful or terrible is, in part, up to us.” ― William MacAskill, What We Owe the Future</p>
    </footer>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-Y2C3F7G3VW
