<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sam Celarek's Portfolio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            padding: 20px;
        }

        #name-box {
            background-color: gray;
            padding: 5px 20px;
            font-weight: bold;
            border-radius: 5px;
            display: inline-block;
            color: white;
        }

        .centered {
            text-align: center;
            margin-top: 20px;
        }

        .description {
            margin-bottom: 20px;
        }

        a {
            display: block;
            margin: 10px 0;
            color: #007BFF;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>

<div id="name-box">The Data Dude:</div>

<div class="centered description">
    Hello! I've been a nurse for the past 8 years, working on teams and leveraging data to enhance hospital KPIs and optimize floor staffing. After completing my BrainStation Data Science Diploma, I'm on the lookout for my first role in the industry. Take a glance at some of my data science projects below and feel free to connect!
</div>

<div class="centered">
    <a href="https://www.linkedin.com/in/sam-celarek/">View My LinkedIn Profile</a>
    <a href="https://github.com/scelarek">View My GitHub Profile</a>
</div>

</body>
</html>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
